### ISSUE TITLE
A different approach for deactivation when Update Manager is not present

### ISSUE THREAD

**Issue by johnalarcon** [xxsimoxx/stats-for-update-manager#19]
I'm writing a new extension for Update Manager and wanted to share some findings that may be useful for the Stats extension. When deactivating the Update Manager plugin, the Stats extension deactivates itself to prevent warnings/errors. This seems like a good way, but, I've found it's quite easy to forget to reactivate the extension afterward. I'm proposing an alternate method with this feature request.

**Describe the functions you wish to be added**
No additional functions are needed.

**Describe alternatives you've considered**
Rather than deactivating the extension, its primary constructor ([at line 66](https://github.com/xxsimoxx/stats-for-update-manager/blob/26a2b8727c16a946ac4f1a29984a0dd85a11301f/stats-for-update-manager.php#L62)) could simply `return` if the Update Manager plugin is inactive. This would keep the extension activated without running code that might cause warnings/errors, and it would mean the extension is automatically active when the Update Manager plugin is active. This would also make it possible to remove all the code in the extension related to deactivating and creating an admin notice when Update Manager is not found. This is the approach I've taken in my new extension – it works great and requires exceptionally little code.

**Have you already some code that could help?**
- [x] Yes
- [ ] No

**Proposed Change**
Add the following check to the Stats extension's constructor to prevent running the extension (rather than fully deactivating it) if Update Manager is not present.
```
if (is_plugin_active('codepotent-update-manger/codepotent-update-manger.php)) {
    return
}
```
...and remove the code related to auto-deactivation and admin notice.

**Comment by xxsimoxx** [comment]
Yes, I've come into this several times.
You suggested to return on line 66.
I've returned a bit later to ensure that deactivation and uninstall are properly handled and the cron job is removed.
Do you think it's right?

**Comment by xxsimoxx** [comment]
I've released [1.3.0](https://github.com/xxsimoxx/stats-for-update-manager/releases/download/v1.3.0/stats-for-update-manager-1.3.0.zip) (but not pushed updates).
Please let me know if it works as espected.
Thank you.
Simone.

**Comment by johnalarcon** [comment]
That will work, although it does add a slight issue – for example, calling the activation/deactivation methods when the plugin isn't actually being activated/deactivated...can be confusing for someone reading the code. Or, if someone uses the code as an example for creating an extension, they might perpetuate the issue in their own code, not realizing what you're _actually_ doing. I think it's better to return early before running those methods, simply for the clarity it provides.

A possible solution could be to introduce two new methods, something like `is_update_manager_active()` and `toggle_cron_jobs()` to replace the current `disable_cron()` method.  The first method would check for whether Update Manager is active or not, and the second function would react to the result of that first function and toggle (add/remove) the cron job. You could then use that method in your activation method, ie, `toggle_cron_jobs(true)`, and in the deactivation method, ie, `toggle_cron_jobs(false)` and avoid calling the activation/deactivation methods in a way that may lead to confusion later, and provides clarity for the code being executed.

**Comment by xxsimoxx** [comment]
Just done some tests and like to share my thoughts with you.
I've pushed changes to the repo.

I've moved the uninstall code to `uninstall.php`, that seems the best approach to meet with codex standards:

> The plugin should not run arbitrary code outside of functions

and also ensures that the database is deleted when unistalling.
If (as example) I'm moving my update server to a dedicated WP installation if I first remove UM and then SFUM and the uninstall code is not activated the database is kept.

Registering activation and deactivation hook should stay in place even if UM is not running:
- If I'm going to install first SFUM and then UM and the activation is not called the database table will not be created
- If I deactivate the plugin my expectations are that the table is not modified by the cron job, so I have to deactivate it

Also cron job must stay in place, because if the plugin is active it must keep deleting old logs to conform with privacy policy.

What do you think about?
Thank you!
Simone.
